select id as invoice_advance_id,
       upper(state) as invoice_advance_state,
       business_product_id,
       business_id,
       customer_id,
       advance_amount,
       effective_advance,
       effective_collection,
       fee_at_due,
       repayment_amount,
       due_date as due_datetime,
       cast(due_date as date) as due_date,
       currency,
       advance_date as advance_datetime,
       cast(advance_date as date) as advance_date,
       grace_period_ends_at as grace_period_ends_at_datetime,
       cast(grace_period_ends_at as date) as grace_period_ends_at,
       created_at as created_at_datetime,
       cast(created_at as date) as created_at_date,
       requested_at as requested_at_datetime,
       cast(requested_at as date) as requested_at_date,
       updated_at as updated_at_datetime,
       cast(updated_at as date) as updated_at_date,
       paid_at as paid_at_datetime,
       cast(paid_at as date) as paid_at_date,
       version,
       _fivetran_deleted,
       _fivetran_synced,
       total
from {{ source('mundi', 'INVOICE_ADVANCE') }}