select id as invoice_advance_id,
       state,
       business_product_id,
       business_id,
       customer_id,
       advance_amount,
       effective_advance,
       effective_collection,
       fee_at_due,
       repayment_amount,
       due_date,
       currency,
       advance_date,
       grace_period_ends_at,
       created_at,
       requested_at,
       updated_at,
       paid_at,
       version,
       _fivetran_deleted,
       _fivetran_synced,
       total
from {{ source('mundi', 'INVOICE_ADVANCE') }}